# Generated by Django 4.1.6 on 2023-03-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
