# Generated by Django 4.1.6 on 2023-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_salesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('registerDate', models.DateField()),
            ],
        ),
    ]
