# Generated by Django 4.1.6 on 2023-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
